### ISSUE TITLE
2016 News Revamp - Tracking List

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSU-News-2016#1]
## News Theme
- [ ] Style and handling for gallery shortcode.
- [ ] Post formats - video, post, gallery.
- [ ] Feature article layout builder for home page and topic pages.
- [ ] Popular articles algorithm.
  - [ ] Reach out to other groups, research how to define this.
- [ ] Editors picks feeds.
- [ ] Related articles on each page from other WSU sites using our infrastructure.
- [ ] Social sharing - customize headlines for various social sites.
- [ ] Pull in additional feeds.
- [ ] Secondary by-lines showing author organization, saved as post meta for eternity.
## Newsletter
- [ ] Custom HTML template.
- [ ] Drag and Drop news story builder, similar to announcements.
## Content Syndication
- [ ] Ability to pull custom fields, like sub-headline.
- [ ] Ability to pull various image sizes.
## General
- [ ] Ability for outside users to submit a story through WordPress.
- [ ] Send a new story from one site to another.
- [ ] Community and WSU News photo submission with approval, editing process.
- [ ] Split announcements.wsu.edu from news.wsu.edu.
- [ ] Publicize on social networks when article is posted. (?)

**Comment by slocker3** [comment]
GA tracking on Announcements newsletter
GA tracking on WSUNews newsletter
